from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(547, 531)
        MainWindow.setMinimumSize(QtCore.QSize(547, 531))
        MainWindow.setMaximumSize(QtCore.QSize(547, 531))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.stackedWidget.setObjectName("stackedWidget")
        self.connectPage = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.connectPage.sizePolicy().hasHeightForWidth())
        self.connectPage.setSizePolicy(sizePolicy)
        self.connectPage.setObjectName("connectPage")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.connectPage)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(-1, -1, 9, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.GeneralBox = QtWidgets.QGroupBox(self.connectPage)
        self.GeneralBox.setStyleSheet("\n"
"")
        self.GeneralBox.setObjectName("GeneralBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.GeneralBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.PortLabel = QtWidgets.QLabel(self.GeneralBox)
        self.PortLabel.setAutoFillBackground(False)
        self.PortLabel.setObjectName("PortLabel")
        self.gridLayout_2.addWidget(self.PortLabel, 0, 3, 1, 1)
        self.HostnameLabel = QtWidgets.QLabel(self.GeneralBox)
        self.HostnameLabel.setEnabled(True)
        self.HostnameLabel.setObjectName("HostnameLabel")
        self.gridLayout_2.addWidget(self.HostnameLabel, 0, 0, 1, 1)
        self.PortText = QtWidgets.QLineEdit(self.GeneralBox)
        self.PortText.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.PortText.setText("")
        self.PortText.setObjectName("PortText")
        self.gridLayout_2.addWidget(self.PortText, 0, 4, 1, 1)
        self.hostnameText = QtWidgets.QLineEdit(self.GeneralBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostnameText.sizePolicy().hasHeightForWidth())
        self.hostnameText.setSizePolicy(sizePolicy)
        self.hostnameText.setMouseTracking(True)
        self.hostnameText.setText("")
        self.hostnameText.setObjectName("hostnameText")
        self.gridLayout_2.addWidget(self.hostnameText, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.GeneralBox, 1, 0, 1, 1)
        self.Layout1 = QtWidgets.QHBoxLayout()
        self.Layout1.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.Layout1.setObjectName("Layout1")
        self.HelpButton = QtWidgets.QToolButton(self.connectPage)
        self.HelpButton.setObjectName("HelpButton")
        self.Layout1.addWidget(self.HelpButton)
        self.SettingButton = QtWidgets.QToolButton(self.connectPage)
        self.SettingButton.setObjectName("SettingButton")
        self.Layout1.addWidget(self.SettingButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.Layout1.addItem(spacerItem1)
        self.gridLayout_4.addLayout(self.Layout1, 0, 0, 1, 1)
        self.ServerInfoBox = QtWidgets.QGroupBox(self.connectPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ServerInfoBox.sizePolicy().hasHeightForWidth())
        self.ServerInfoBox.setSizePolicy(sizePolicy)
        self.ServerInfoBox.setMinimumSize(QtCore.QSize(503, 316))
        self.ServerInfoBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ServerInfoBox.setStyleSheet("")
        self.ServerInfoBox.setFlat(False)
        self.ServerInfoBox.setCheckable(False)
        self.ServerInfoBox.setChecked(False)
        self.ServerInfoBox.setObjectName("ServerInfoBox")
        self.gridLayout = QtWidgets.QGridLayout(self.ServerInfoBox)
        self.gridLayout.setObjectName("gridLayout")
        self.ServerNameLabel = QtWidgets.QLabel(self.ServerInfoBox)
        self.ServerNameLabel.setObjectName("ServerNameLabel")
        self.gridLayout.addWidget(self.ServerNameLabel, 0, 0, 1, 1)
        self.ServerTable = QtWidgets.QTableWidget(self.ServerInfoBox)
        self.ServerTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ServerTable.sizePolicy().hasHeightForWidth())
        self.ServerTable.setSizePolicy(sizePolicy)
        self.ServerTable.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeMode.ResizeToContents)
        self.ServerTable.setMinimumSize(QtCore.QSize(408, 0))
        self.ServerTable.setMaximumSize(QtCore.QSize(408, 235))
        self.ServerTable.setBaseSize(QtCore.QSize(0, 0))
        self.ServerTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.ServerTable.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ServerTable.setAutoFillBackground(False)
        self.ServerTable.setStyleSheet("")
        self.ServerTable.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.ServerTable.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ServerTable.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.ServerTable.setLineWidth(6)
        self.ServerTable.setMidLineWidth(1)
        self.ServerTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ServerTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ServerTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.ServerTable.setAutoScroll(True)
        self.ServerTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.ServerTable.setProperty("showDropIndicator", False)
        self.ServerTable.setDragEnabled(False)
        self.ServerTable.setDragDropOverwriteMode(False)
        self.ServerTable.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.NoDragDrop)
        self.ServerTable.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.ServerTable.setAlternatingRowColors(False)
        self.ServerTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.ServerTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.ServerTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.ServerTable.setShowGrid(True)
        self.ServerTable.setGridStyle(QtCore.Qt.PenStyle.DotLine)
        self.ServerTable.setWordWrap(True)
        self.ServerTable.setCornerButtonEnabled(False)
        self.ServerTable.setRowCount(9)
        self.ServerTable.setColumnCount(3)
        self.ServerTable.setObjectName("ServerTable")
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.ServerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setStrikeOut(False)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.ServerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.ServerTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setBackground(brush)
        self.ServerTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ServerTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ServerTable.setItem(0, 2, item)
        self.ServerTable.horizontalHeader().setVisible(True)
        self.ServerTable.horizontalHeader().setCascadingSectionResizes(False)
        self.ServerTable.horizontalHeader().setHighlightSections(True)
        self.ServerTable.horizontalHeader().setMinimumSectionSize(135)
        self.ServerTable.horizontalHeader().setSortIndicatorShown(False)
        self.ServerTable.horizontalHeader().setStretchLastSection(True)
        self.ServerTable.verticalHeader().setVisible(False)
        self.ServerTable.verticalHeader().setCascadingSectionResizes(False)
        self.ServerTable.verticalHeader().setHighlightSections(True)
        self.ServerTable.verticalHeader().setSortIndicatorShown(False)
        self.ServerTable.verticalHeader().setStretchLastSection(True)
        self.gridLayout.addWidget(self.ServerTable, 3, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ServerNameText = QtWidgets.QLineEdit(self.ServerInfoBox)
        self.ServerNameText.setText("")
        self.ServerNameText.setObjectName("ServerNameText")
        self.horizontalLayout_2.addWidget(self.ServerNameText)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.Layout2 = QtWidgets.QVBoxLayout()
        self.Layout2.setObjectName("Layout2")
        self.AddServerButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.AddServerButton.setObjectName("AddServerButton")
        self.Layout2.addWidget(self.AddServerButton)
        self.LoadServerButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.LoadServerButton.setObjectName("LoadServerButton")
        self.Layout2.addWidget(self.LoadServerButton)
        self.DeleteServerButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.DeleteServerButton.setAutoDefault(False)
        self.DeleteServerButton.setDefault(False)
        self.DeleteServerButton.setFlat(False)
        self.DeleteServerButton.setObjectName("DeleteServerButton")
        self.Layout2.addWidget(self.DeleteServerButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.Layout2.addItem(spacerItem2)
        self.ImportButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.ImportButton.setObjectName("ImportButton")
        self.Layout2.addWidget(self.ImportButton)
        self.ExportButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.ExportButton.setObjectName("ExportButton")
        self.Layout2.addWidget(self.ExportButton)
        self.gridLayout.addLayout(self.Layout2, 3, 1, 1, 1)
        self.gridLayout_4.addWidget(self.ServerInfoBox, 2, 0, 1, 1)
        self.miscgroupBox = QtWidgets.QGroupBox(self.connectPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.miscgroupBox.sizePolicy().hasHeightForWidth())
        self.miscgroupBox.setSizePolicy(sizePolicy)
        self.miscgroupBox.setTitle("")
        self.miscgroupBox.setObjectName("miscgroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.miscgroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ConnectButton = QtWidgets.QPushButton(self.miscgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectButton.sizePolicy().hasHeightForWidth())
        self.ConnectButton.setSizePolicy(sizePolicy)
        self.ConnectButton.setObjectName("ConnectButton")
        self.horizontalLayout_6.addWidget(self.ConnectButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.CancelConnectButton = QtWidgets.QPushButton(self.miscgroupBox)
        self.CancelConnectButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CancelConnectButton.sizePolicy().hasHeightForWidth())
        self.CancelConnectButton.setSizePolicy(sizePolicy)
        self.CancelConnectButton.setObjectName("CancelConnectButton")
        self.horizontalLayout_6.addWidget(self.CancelConnectButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.SSLButton = QtWidgets.QRadioButton(self.miscgroupBox)
        self.SSLButton.setEnabled(True)
        self.SSLButton.setChecked(False)
        self.SSLButton.setObjectName("SSLButton")
        self.verticalLayout_2.addWidget(self.SSLButton)
        self.gridLayout_4.addWidget(self.miscgroupBox, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.connectPage)
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.loginPage)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.loginBox = QtWidgets.QGroupBox(self.loginPage)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.loginBox.setFont(font)
        self.loginBox.setObjectName("loginBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.loginBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.loginBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.usernameText = QtWidgets.QLineEdit(self.loginBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.usernameText.sizePolicy().hasHeightForWidth())
        self.usernameText.setSizePolicy(sizePolicy)
        self.usernameText.setClearButtonEnabled(True)
        self.usernameText.setObjectName("usernameText")
        self.verticalLayout_4.addWidget(self.usernameText)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.loginBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.passwordText = QtWidgets.QLineEdit(self.loginBox)
        self.passwordText.setBaseSize(QtCore.QSize(0, 0))
        self.passwordText.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhHiddenText|QtCore.Qt.InputMethodHint.ImhNoAutoUppercase|QtCore.Qt.InputMethodHint.ImhNoPredictiveText|QtCore.Qt.InputMethodHint.ImhPreferLatin|QtCore.Qt.InputMethodHint.ImhSensitiveData|QtCore.Qt.InputMethodHint.ImhUppercaseOnly)
        self.passwordText.setText("")
        self.passwordText.setMaxLength(32767)
        self.passwordText.setFrame(True)
        self.passwordText.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordText.setCursorMoveStyle(QtCore.Qt.CursorMoveStyle.LogicalMoveStyle)
        self.passwordText.setClearButtonEnabled(True)
        self.passwordText.setObjectName("passwordText")
        self.verticalLayout_5.addWidget(self.passwordText)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.remeberMeRadio = QtWidgets.QRadioButton(self.loginBox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.remeberMeRadio.setFont(font)
        self.remeberMeRadio.setObjectName("remeberMeRadio")
        self.horizontalLayout.addWidget(self.remeberMeRadio)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem10)
        self.resetPasswordButton = QtWidgets.QPushButton(self.loginBox)
        self.resetPasswordButton.setObjectName("resetPasswordButton")
        self.horizontalLayout.addWidget(self.resetPasswordButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.signinButton = QtWidgets.QPushButton(self.loginBox)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.signinButton.setFont(font)
        self.signinButton.setObjectName("signinButton")
        self.verticalLayout.addWidget(self.signinButton)
        self.registerButton = QtWidgets.QPushButton(self.loginBox)
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton)
        self.gridLayout_5.addWidget(self.loginBox, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.loginPage)
        self.gridLayout_3.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.GeneralBox.setTitle(_translate("MainWindow", "General"))
        self.PortLabel.setText(_translate("MainWindow", "Port:"))
        self.HostnameLabel.setText(_translate("MainWindow", "Hostname:"))
        self.HelpButton.setText(_translate("MainWindow", "Help"))
        self.SettingButton.setText(_translate("MainWindow", "Settings"))
        self.ServerInfoBox.setTitle(_translate("MainWindow", "Add, Load, Delete Server"))
        self.ServerNameLabel.setText(_translate("MainWindow", "Server Name:"))
        self.ServerTable.setSortingEnabled(False)
        item = self.ServerTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Server Name"))
        item = self.ServerTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hostname"))
        item = self.ServerTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Port"))
        __sortingEnabled = self.ServerTable.isSortingEnabled()
        self.ServerTable.setSortingEnabled(False)
        item = self.ServerTable.item(0, 0)
        item.setText(_translate("MainWindow", "Loop Back"))
        item = self.ServerTable.item(0, 1)
        item.setText(_translate("MainWindow", "127.0.0.1"))
        item = self.ServerTable.item(0, 2)
        item.setText(_translate("MainWindow", "9090"))
        self.ServerTable.setSortingEnabled(__sortingEnabled)
        self.AddServerButton.setText(_translate("MainWindow", "Add"))
        self.LoadServerButton.setText(_translate("MainWindow", "Load"))
        self.DeleteServerButton.setText(_translate("MainWindow", "Delete"))
        self.ImportButton.setText(_translate("MainWindow", "Import"))
        self.ExportButton.setText(_translate("MainWindow", "Export"))
        self.ConnectButton.setText(_translate("MainWindow", "Connect"))
        self.CancelConnectButton.setText(_translate("MainWindow", "Cancel"))
        self.SSLButton.setText(_translate("MainWindow", "SSL Encryption"))
        self.loginBox.setTitle(_translate("MainWindow", "Login"))
        self.label.setText(_translate("MainWindow", "Username:"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.remeberMeRadio.setText(_translate("MainWindow", "Remeber login"))
        self.resetPasswordButton.setText(_translate("MainWindow", "Reset Password"))
        self.signinButton.setText(_translate("MainWindow", "Sign in"))
        self.registerButton.setText(_translate("MainWindow", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
