from PySide6 import QtCore, QtGui, QtWidgets


class Ui_ConnectWindow(object):
    def setupUi(self, ConnectWindow : QtGui.QWindow):
        ConnectWindow.setObjectName("ConnectWindow")
        ConnectWindow.resize(521, 506)
        ConnectWindow.setMinimumSize(521, 506)
        ConnectWindow.setMaximumSize(521, 506)
        ConnectWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(ConnectWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.Layout1_2 = QtWidgets.QHBoxLayout()
        self.Layout1_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.Layout1_2.setObjectName("Layout1_2")
        self.HelpButton = QtWidgets.QToolButton(self.centralwidget)
        self.HelpButton.setObjectName("HelpButton")
        self.Layout1_2.addWidget(self.HelpButton)
        self.SettingsButton = QtWidgets.QToolButton(self.centralwidget)
        self.SettingsButton.setObjectName("SettingsButton")
        self.Layout1_2.addWidget(self.SettingsButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.Layout1_2.addItem(spacerItem)
        self.gridLayout_6.addLayout(self.Layout1_2, 0, 0, 1, 1)
        self.GeneralBox = QtWidgets.QGroupBox(self.centralwidget)
        self.GeneralBox.setStyleSheet("")
        self.GeneralBox.setObjectName("GeneralBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.GeneralBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.PortLabel = QtWidgets.QLabel(self.GeneralBox)
        self.PortLabel.setAutoFillBackground(False)
        self.PortLabel.setObjectName("PortLabel")
        self.gridLayout_3.addWidget(self.PortLabel, 0, 3, 1, 1)
        self.HostnameLabel = QtWidgets.QLabel(self.GeneralBox)
        self.HostnameLabel.setEnabled(True)
        self.HostnameLabel.setObjectName("HostnameLabel")
        self.gridLayout_3.addWidget(self.HostnameLabel, 0, 0, 1, 1)
        self.PortText = QtWidgets.QLineEdit(self.GeneralBox)
        self.PortText.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhDigitsOnly)
        self.PortText.setText("")
        self.PortText.setObjectName("PortText")
        self.gridLayout_3.addWidget(self.PortText, 0, 4, 1, 1)
        self.hostnameText = QtWidgets.QLineEdit(self.GeneralBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hostnameText.sizePolicy().hasHeightForWidth())
        self.hostnameText.setSizePolicy(sizePolicy)
        self.hostnameText.setMouseTracking(True)
        self.hostnameText.setText("")
        self.hostnameText.setObjectName("hostnameText")
        self.gridLayout_3.addWidget(self.hostnameText, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_6.addWidget(self.GeneralBox, 1, 0, 1, 1)
        self.ServerInfoBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ServerInfoBox.sizePolicy().hasHeightForWidth())
        self.ServerInfoBox.setSizePolicy(sizePolicy)
        self.ServerInfoBox.setMinimumSize(QtCore.QSize(503, 316))
        self.ServerInfoBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ServerInfoBox.setStyleSheet("")
        self.ServerInfoBox.setFlat(False)
        self.ServerInfoBox.setCheckable(False)
        self.ServerInfoBox.setChecked(False)
        self.ServerInfoBox.setObjectName("ServerInfoBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.ServerInfoBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.ServerNameLabel = QtWidgets.QLabel(self.ServerInfoBox)
        self.ServerNameLabel.setObjectName("ServerNameLabel")
        self.gridLayout_7.addWidget(self.ServerNameLabel, 0, 0, 1, 1)
        self.ServerTable = QtWidgets.QTableWidget(self.ServerInfoBox)
        self.ServerTable.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ServerTable.sizePolicy().hasHeightForWidth())
        self.ServerTable.setSizePolicy(sizePolicy)
        self.ServerTable.setMinimumSize(QtCore.QSize(408, 0))
        self.ServerTable.setMaximumSize(QtCore.QSize(408, 235))
        self.ServerTable.setBaseSize(QtCore.QSize(0, 0))
        self.ServerTable.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.ServerTable.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.ServerTable.setAutoFillBackground(False)
        self.ServerTable.setStyleSheet("")
        self.ServerTable.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.ServerTable.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ServerTable.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.ServerTable.setLineWidth(6)
        self.ServerTable.setMidLineWidth(1)
        self.ServerTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ServerTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.ServerTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.ServerTable.setAutoScroll(True)
        self.ServerTable.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.DoubleClicked|QtWidgets.QAbstractItemView.EditTrigger.EditKeyPressed)
        self.ServerTable.setProperty("showDropIndicator", False)
        self.ServerTable.setDragEnabled(False)
        self.ServerTable.setDragDropOverwriteMode(False)
        self.ServerTable.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.NoDragDrop)
        self.ServerTable.setDefaultDropAction(QtCore.Qt.DropAction.IgnoreAction)
        self.ServerTable.setAlternatingRowColors(False)
        self.ServerTable.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.ServerTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.ServerTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollMode.ScrollPerItem)
        self.ServerTable.setShowGrid(True)
        self.ServerTable.setGridStyle(QtCore.Qt.PenStyle.DotLine)
        self.ServerTable.setWordWrap(True)
        self.ServerTable.setCornerButtonEnabled(False)
        self.ServerTable.setRowCount(9)
        self.ServerTable.setColumnCount(3)
        self.ServerTable.setObjectName("ServerTable")
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.ServerTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setStrikeOut(False)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.ServerTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        item.setForeground(brush)
        self.ServerTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        item.setBackground(brush)
        self.ServerTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ServerTable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ServerTable.setItem(0, 2, item)
        self.ServerTable.horizontalHeader().setVisible(True)
        self.ServerTable.horizontalHeader().setCascadingSectionResizes(False)
        self.ServerTable.horizontalHeader().setHighlightSections(True)
        self.ServerTable.horizontalHeader().setMinimumSectionSize(135)
        self.ServerTable.horizontalHeader().setSortIndicatorShown(False)
        self.ServerTable.horizontalHeader().setStretchLastSection(True)
        self.ServerTable.verticalHeader().setVisible(False)
        self.ServerTable.verticalHeader().setCascadingSectionResizes(False)
        self.ServerTable.verticalHeader().setHighlightSections(True)
        self.ServerTable.verticalHeader().setSortIndicatorShown(False)
        self.ServerTable.verticalHeader().setStretchLastSection(True)
        self.gridLayout_7.addWidget(self.ServerTable, 3, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ServerNameText = QtWidgets.QLineEdit(self.ServerInfoBox)
        self.ServerNameText.setText("")
        self.ServerNameText.setObjectName("ServerNameText")
        self.horizontalLayout_4.addWidget(self.ServerNameText)
        self.gridLayout_7.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.Layout2_2 = QtWidgets.QVBoxLayout()
        self.Layout2_2.setObjectName("Layout2_2")
        self.AddServerButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.AddServerButton.setObjectName("AddServerButton")
        self.Layout2_2.addWidget(self.AddServerButton)
        self.LoadServerButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.LoadServerButton.setObjectName("LoadServerButton")
        self.Layout2_2.addWidget(self.LoadServerButton)
        self.DeleteServerButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.DeleteServerButton.setAutoDefault(False)
        self.DeleteServerButton.setDefault(False)
        self.DeleteServerButton.setFlat(False)
        self.DeleteServerButton.setObjectName("DeleteServerButton")
        self.Layout2_2.addWidget(self.DeleteServerButton)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.Layout2_2.addItem(spacerItem2)
        self.ImportButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.ImportButton.setObjectName("ImportButton")
        self.Layout2_2.addWidget(self.ImportButton)
        self.ExportButton = QtWidgets.QPushButton(self.ServerInfoBox)
        self.ExportButton.setObjectName("ExportButton")
        self.Layout2_2.addWidget(self.ExportButton)
        self.gridLayout_7.addLayout(self.Layout2_2, 3, 1, 1, 1)
        self.gridLayout_6.addWidget(self.ServerInfoBox, 2, 0, 1, 1)
        self.miscgroupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.miscgroupBox.sizePolicy().hasHeightForWidth())
        self.miscgroupBox.setSizePolicy(sizePolicy)
        self.miscgroupBox.setTitle("")
        self.miscgroupBox.setObjectName("miscgroupBox")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.miscgroupBox)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ConnectButton = QtWidgets.QPushButton(self.miscgroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ConnectButton.sizePolicy().hasHeightForWidth())
        self.ConnectButton.setSizePolicy(sizePolicy)
        self.ConnectButton.setObjectName("ConnectButton")
        self.horizontalLayout_7.addWidget(self.ConnectButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.CancelConnectButton = QtWidgets.QPushButton(self.miscgroupBox)
        self.CancelConnectButton.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CancelConnectButton.sizePolicy().hasHeightForWidth())
        self.CancelConnectButton.setSizePolicy(sizePolicy)
        self.CancelConnectButton.setObjectName("CancelConnectButton")
        self.horizontalLayout_7.addWidget(self.CancelConnectButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.SSLButton = QtWidgets.QRadioButton(self.miscgroupBox)
        self.SSLButton.setEnabled(True)
        self.SSLButton.setChecked(False)
        self.SSLButton.setObjectName("SSLButton")
        self.verticalLayout_6.addWidget(self.SSLButton)
        self.gridLayout_6.addWidget(self.miscgroupBox, 3, 0, 1, 1)
        ConnectWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConnectWindow)
        QtCore.QMetaObject.connectSlotsByName(ConnectWindow)

    def retranslateUi(self, ConnectWindow):
        _translate = QtCore.QCoreApplication.translate
        ConnectWindow.setWindowTitle(_translate("ConnectWindow", "TCP Chat Client"))
        self.HelpButton.setText(_translate("ConnectWindow", "Help"))
        self.SettingsButton.setText(_translate("ConnectWindow", "Settings"))
        self.GeneralBox.setTitle(_translate("ConnectWindow", "General"))
        self.PortLabel.setText(_translate("ConnectWindow", "Port:"))
        self.HostnameLabel.setText(_translate("ConnectWindow", "Hostname:"))
        self.ServerInfoBox.setTitle(_translate("ConnectWindow", "Add, Load, Delete Server"))
        self.ServerNameLabel.setText(_translate("ConnectWindow", "Server Name:"))
        self.ServerTable.setSortingEnabled(False)
        item = self.ServerTable.horizontalHeaderItem(0)
        item.setText(_translate("ConnectWindow", "Server Name"))
        item = self.ServerTable.horizontalHeaderItem(1)
        item.setText(_translate("ConnectWindow", "Hostname"))
        item = self.ServerTable.horizontalHeaderItem(2)
        item.setText(_translate("ConnectWindow", "Port"))
        __sortingEnabled = self.ServerTable.isSortingEnabled()
        self.ServerTable.setSortingEnabled(False)
        item = self.ServerTable.item(0, 0)
        item.setText(_translate("ConnectWindow", "Loop Back"))
        item = self.ServerTable.item(0, 1)
        item.setText(_translate("ConnectWindow", "127.0.0.1"))
        item = self.ServerTable.item(0, 2)
        item.setText(_translate("ConnectWindow", "9090"))
        self.ServerTable.setSortingEnabled(__sortingEnabled)
        self.AddServerButton.setText(_translate("ConnectWindow", "Add"))
        self.LoadServerButton.setText(_translate("ConnectWindow", "Load"))
        self.DeleteServerButton.setText(_translate("ConnectWindow", "Delete"))
        self.ImportButton.setText(_translate("ConnectWindow", "Import"))
        self.ExportButton.setText(_translate("ConnectWindow", "Export"))
        self.ConnectButton.setText(_translate("ConnectWindow", "Connect"))
        self.CancelConnectButton.setText(_translate("ConnectWindow", "Cancel"))
        self.SSLButton.setText(_translate("ConnectWindow", "SSL Encryption"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ConnectWindow = QtWidgets.QMainWindow()
    ui = Ui_ConnectWindow()
    ui.setupUi(ConnectWindow)
    ConnectWindow.show()
    sys.exit(app.exec())
